[project]
name = "bctidemcpremote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "pydantic-settings>=2.12.0",
    "scalekit-sdk-python>=2.4.15",
    "uvicorn>=0.40.0",
]
